version: '3'

services:
  mariadb:
    image: mariadb:10.4
    expose:
      # Expose mariadb port to php service (access as hostname "mariadb" from within php container)
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: db
      MARIADB_DATABASE: db
      MARIADB_USER: db
      MARIADB_PASSWORD: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    expose:
      - '8080'
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
